### ISSUE TITLE
s3 url not found (404) problem

### ISSUE THREAD

**Issue by Tuhaj** [tedconf/ember-cli-front-end-builds#13]
Hey! 

I'm not sure if the url the app is setting for the assets is ok.

I configured the serverside and frontside. The server side gets the notifications and creates records with the apps in the db. It has problems with fetching the data from given urls in the endpoint columns. 

The app urls in the database are beginning with 

`https://s3.amazonaws.com/`

And the fetch action from the rails side cannot get the files.

The files are available at url:
`https://my-app.s3.amazonaws.com`

I get the following message from amazon:

"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint." 

My bucket policy:

```

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadForGetBucketObjects",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::MY-BUCKET-NAME/*"
        }
    ]
}
```

// Brocfile.js

```
var app = new EmberApp({
  'fingerprint': {
    prepend: "https://s3.amazonaws.com/my-app/dist/"
  }
});
```

**Comment by hhff** [comment]
Sounds to me like your bucket is something other than "US Standard"

**Comment by Tuhaj** [comment]
hmmm.. can be. I'll check it.

**Comment by Tuhaj** [comment]
Impossible! It works! Great job with ember-cli-front-end-builds :+1:

**Comment by ryanto** [comment]
Glad to hear! Let us know if you have any more issues.

Also, could you let us know what did you do to fix this, just in case someone else has this same problem.

**Comment by hhff** [comment]
If it's that US standard bucket thing - it would be good to put that in the readme!

**Comment by ryanto** [comment]
Ok, I put in a note about using something other than us standard region. Thanks guys!
