### ISSUE TITLE
Compiling seems to output links to assets without including prefixes

### ISSUE THREAD

**Issue by dza2000** [tedconf/ember-cli-front-end-builds#16]
So in running the deployment, I was expecting my output HTML that is saved back to the rails DB to have references to the actual prefixed folder in S3.  So, like this:

```
http://s3.address.bucket_name/prefix/prefix-build-SHA/assets/file_name.js
```

But what I got was 

```
assets/file_name.js
```

My guess is that invariably I did something wrong, but I'm not totally sure.  So, I'm not sure if this is really an issue or if I'm the issue.

**Comment by samselikoff** [comment]
I believe this is because `ember deploy --environment development` (or just `ember deploy`) will both build your app with `--environment=development`, as well as use the `development` key of your `deploy.js`. We need to add an option to build with prod environment even if your deploy env is something other than `production`.

@ryanto thoughts?

**Comment by samselikoff** [comment]
Here's the line: https://github.com/tedconf/ember-cli-front-end-builds/blob/master/lib/commands/deploy.js#L28

We just need to add an option `--build-environment` flag and check for it here

**Comment by ryanto** [comment]
We can add an additional build-environment.

@dza2000 you need to setup asset fingerprinting in your Brocfile. See: https://github.com/tedconf/ember-cli-front-end-builds#ember-app-setup This will automatically be enabled for production environment, if you are deploying a non prod env, like staging, you need to pass `enabled: true` to that fingerprint hash.

**Comment by dza2000** [comment]
@ryanto looks like that works, except for one thing... how would I include the `distPrefix` in that brocfile?  We're wanting to have our folder be this: 

```
front-end-builds-{{SHA}}
```

and not just `front-end-builds`.  Other than that, this is working great.

**Comment by ryanto** [comment]
Currently not supported. We're just serving out of `/dist/` and since all the assets are fingerprinted there are some caching wins when things don't change.

Happy to add this feature, but I'd like to understand your use case for serving out of `front-end-builds-{{SHA}}` vs just `front-end-builds`?

**Comment by dza2000** [comment]
@ryanto I think my superiors want to be able to hang on to every version of the code so we can roll back to something earlier if necessary using the front-end-builds gem in rails. I don't necessarily think this would affect that ability, however.

**Comment by ryanto** [comment]
Yup. We have the same requirements at TED. Since all assets are fingerprinted they'll live forever in dist, which allows you to rollback/forward to any versions that are in front end builds.

Deploying to a sha-less /dist/ works perfect for this.

**Comment by dza2000** [comment]
Awesome, thanks so much!
