### ISSUE TITLE
Deprecation warning after upgrading to ember-cli ~1.13.1

### ISSUE THREAD

**Issue by heygrady** [tedconf/ember-cli-front-end-builds#22]
```
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
```

Upgraded to the latest Ember CLI and started getting deprecation warnings related to the use of `silent.js`. This functionality has been moved out to another library.

https://github.com/ember-cli/ember-cli/issues/4397
https://github.com/ember-cli/silent-error

**Comment by mmahalwy** [comment]
Getting this on 1.13.8
