### ISSUE TITLE
Better Document AWS Configuration

### ISSUE THREAD

**Issue by hhff** [tedconf/ember-cli-front-end-builds#8]
Hi Guys!

Loved the talk at EmberNYC.  In the process of setting this up - but I've never used S3 for static website hosting.  What's best configuration for front_end_builds?  Happy to PR the README once I've got it down...

hx

**Comment by hhff** [comment]
Ok so, using a Policy such as:

``` js
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadForGetBucketObjects",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::my-bucket-name/*"
        }
    ]
}
```

Allows my rails server to pull in the new index.html

However now the index.html file is loading correctly from the rails server, but the CSS & JS assets are not being found.  It's attempting to pull them from relative paths like `my-rails-server.com/assets/client-{{SHA}}.css` - instead of the full path to S3.

What's the trick here?  Thankyou!

**Comment by samselikoff** [comment]
Hey, thanks for checking the project out! FYI the API is in a lot of flux right now.

Did you run `ember deploy:setup`?

**Comment by hhff** [comment]
yup!  it's all setup:

``` js
module.exports = {
  "production": {
    "assets": {
      "accessKeyId": "xxxxxxxx",
      "secretAccessKey": "xxxxxxxx",
      "bucket": "my-bucket-name",
      "prefix": "dist",
      "distPrefix": "dist-{{SHA}}"
    },
    "index": {
      "app": "my-client-app-name",
      "endpoints": [
        "http://my-rails-server.com"
      ],
      "apiKey": "xxxxxxxx"
    }
  }
};
```

I'm on CLI 0.1.5 for this app though...

**Comment by ryanto** [comment]
Since you're serving your index from rails, but your assets from S3 you'll need to to prepend your production assets in ember-cli (so that they point to the right host).

The docs on ember-cli are a great resource for this: http://www.ember-cli.com/#fingerprinting-and-cdn-urls

You'll want something like 

```
fingerprint: {
  prepend: "https://s3.amazonaws.com/my-bucket/dist"
}
```

This will tell index.html to serve your assets off S3.

Our docs are a little lacking, but it's something we plan on improving once we get the API a bit more stable. Let us know how everything works out and what causes trouble so we know where to focus our attention when improving things.

Also let us know if you get stuck anywhere. We're glad to help/walk you through the setup.

**Comment by hhff** [comment]
Got it - thankyou @ryanto !

So i understand - does the dir `/bucket/dist` symlink to `/bucket/dist-{{SHA}}` or something?  Just trying to mentally understand the structure.

ty!

**Comment by ryanto** [comment]
Right now it uploads twice....
- Once to `dist` (so all builds are in dist, and index.html is the most recent build)
- and then once to `dist-{{SHA}}` so you have an isolated folder with only that SHA's build.

We recommend fingerprinting your assets and serving them out of s shared dist. That works best for dealing with browser/cdn caches.

**Comment by hhff** [comment]
Thankyou!  I've almost got everything going.  One last question!

If I want to host my frontend at the root of my app - how do I do this?

I'm currently using ActiveAdmin for my backend:

``` ruby
  # Frontend
  front_end 'my-ember-app', '/'

  # Backend
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount FrontEndBuilds::Engine, at: '/admin/builds'
  end
```

But this means now I can't access any of my `/admin` rails routes.  Am I missing something here?

**Comment by ryanto** [comment]
Define the front_end as the last line in the `config/routes`. That way any routes before it will take precedent and your admin areas will work as expected.

Edit: fixed typo, wrong file given :)

**Comment by hhff** [comment]
gah of course

thanks @ryanto !

got everything up and running now from the ember side.  noticed a bug with the rails engine, where it seems all my builds are marked as active, and attempting to deactivate them results in a failed `PUT` request (404).  I'll open it on the Rails repo

Would you like me to add documentation for the above to the README here?

**Comment by ryanto** [comment]
Sure! Thanks.

**Comment by ryanto** [comment]
:+1:
